"""baseline schema

Revision ID: 0d0fe6fc2c74
Revises: 
Create Date: 2026-07-06 17:55:54.410773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d0fe6fc2c74'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('ext_device_id', sa.Text(), nullable=True),
    sa.Column('alias', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('device_id'),
    sa.UniqueConstraint('ext_device_id')
    )
    op.create_table('elf_file',
    sa.Column('elf_file_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.TIMESTAMP(), nullable=True),
    sa.Column('project_name', sa.Text(), nullable=True),
    sa.Column('project_ver', sa.Text(), nullable=True),
    sa.Column('elf_file', sa.LargeBinary(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('project_alias', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('elf_file_id')
    )
    op.create_index('idx_elf_file_project', 'elf_file', ['project_name', 'project_ver'], unique=False)
    op.create_index('idx_elf_file_project_date', 'elf_file', ['project_name', sa.literal_column('date DESC')], unique=False)
    op.create_index('idx_elf_file_project_name', 'elf_file', ['project_name'], unique=False)
    op.create_table('module_elf',
    sa.Column('module_elf_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('app_sha1', sa.CHAR(length=40), nullable=False),
    sa.Column('elf_file', sa.LargeBinary(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('module_elf_id'),
    sa.UniqueConstraint('app_sha1')
    )
    op.create_index('module_elf_app_sha1_idx', 'module_elf', ['app_sha1'], unique=False)
    op.create_table('project_auth',
    sa.Column('project_auth_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.TIMESTAMP(), nullable=True),
    sa.Column('project_name', sa.Text(), nullable=True),
    sa.Column('github', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('project_auth_id')
    )
    op.create_index('idx_project_auth_lookup', 'project_auth', ['project_name', 'github'], unique=False)
    op.create_table('project_settings',
    sa.Column('project_name', sa.Text(), nullable=False),
    sa.Column('device_url_template', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('project_name')
    )
    op.create_table('project_slack_integrations',
    sa.Column('slack_integration_id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.Text(), nullable=True),
    sa.Column('slack_team_id', sa.Text(), nullable=True),
    sa.Column('slack_team_name', sa.Text(), nullable=True),
    sa.Column('slack_channel_id', sa.Text(), nullable=True),
    sa.Column('slack_channel_name', sa.Text(), nullable=True),
    sa.Column('slack_access_token', sa.Text(), nullable=True),
    sa.Column('created_date', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('github_user', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('slack_integration_id')
    )
    op.create_index('idx_project_slack_integrations_project', 'project_slack_integrations', ['project_name'], unique=False)
    op.create_index('idx_project_slack_integrations_team', 'project_slack_integrations', ['slack_team_id'], unique=False)
    op.create_table('project_webhooks',
    sa.Column('webhook_id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.Text(), nullable=True),
    sa.Column('webhook_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('webhook_id')
    )
    op.create_table('crash',
    sa.Column('crash_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.TIMESTAMP(), nullable=True),
    sa.Column('project_name', sa.Text(), nullable=True),
    sa.Column('project_ver', sa.Text(), nullable=True),
    sa.Column('crash_dmp', sa.LargeBinary(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('textsearch', postgresql.TSVECTOR(), nullable=True),
    sa.Column('dump', sa.Text(), nullable=True),
    sa.Column('module_names', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('module_map', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.device_id'], ),
    sa.PrimaryKeyConstraint('crash_id')
    )
    op.create_index('idx_crash_project_name_ver', 'crash', ['project_name', 'project_ver'], unique=False)
    op.create_index('textsearch_idx', 'crash', ['textsearch'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###

    # Full-text maintenance trigger on `crash`. Not autogenerated (Alembic
    # doesn't manage functions/triggers) - reproduced verbatim from
    # db_schema.sql so the ORM-built schema matches the live production DB.
    op.execute("""
CREATE OR REPLACE FUNCTION update_textsearch() RETURNS TRIGGER AS $$
DECLARE
    ext_device_id TEXT;
    device_alias TEXT;
    elf_file_id INTEGER;
    project_ver TEXT;
    project_alias TEXT;
BEGIN
    -- Fetch the ext_device_id and alias from the device table
    SELECT d.ext_device_id, d.alias INTO ext_device_id, device_alias
    FROM device d
    WHERE d.device_id = NEW.device_id;

    -- Fetch the project_alias from the elf_file table
    SELECT e.elf_file_id, e.project_alias, e.project_ver INTO elf_file_id, project_alias, project_ver
    FROM elf_file e
    WHERE e.project_name = NEW.project_name AND e.project_ver = NEW.project_ver;

    -- Update the textsearch column
    NEW.textsearch := to_tsvector('english',
        coalesce(NEW.date::TEXT, '') || ' ' ||
        coalesce(NEW.crash_id::TEXT, '') || ' ' ||
        coalesce(ext_device_id, '') || ' ' ||
        coalesce(device_alias, '') || ' ' ||
        coalesce(NEW.device_id::TEXT, '') || ' ' ||
        coalesce(NEW.project_name, '') || ' ' ||
        coalesce(NEW.project_ver, '') || ' ' ||
        coalesce(NEW.dump, '') || ' ' ||
        coalesce(elf_file_id::TEXT, '') || ' ' ||
        coalesce(project_alias, '') || ' ' ||
        coalesce(project_ver, ''));
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


DROP TRIGGER IF EXISTS trigger_update_textsearch ON crash;
CREATE TRIGGER trigger_update_textsearch
BEFORE INSERT OR UPDATE ON crash
FOR EACH ROW EXECUTE FUNCTION update_textsearch();
""")


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS trigger_update_textsearch ON crash")
    op.execute("DROP FUNCTION IF EXISTS update_textsearch()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('textsearch_idx', table_name='crash', postgresql_using='gin')
    op.drop_index('idx_crash_project_name_ver', table_name='crash')
    op.drop_table('crash')
    op.drop_table('project_webhooks')
    op.drop_index('idx_project_slack_integrations_team', table_name='project_slack_integrations')
    op.drop_index('idx_project_slack_integrations_project', table_name='project_slack_integrations')
    op.drop_table('project_slack_integrations')
    op.drop_table('project_settings')
    op.drop_index('idx_project_auth_lookup', table_name='project_auth')
    op.drop_table('project_auth')
    op.drop_index('module_elf_app_sha1_idx', table_name='module_elf')
    op.drop_table('module_elf')
    op.drop_index('idx_elf_file_project_name', table_name='elf_file')
    op.drop_index('idx_elf_file_project_date', table_name='elf_file')
    op.drop_index('idx_elf_file_project', table_name='elf_file')
    op.drop_table('elf_file')
    op.drop_table('device')
    # ### end Alembic commands ###
